---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[smoke]
    attributes:
  - name: ipv6_default
    run_list:
      - recipe[smoke::ipv6_default]
    attributes:
  - name: list_of_tables
    run_list:
      - recipe[smoke::tables]
    attributes:
  - name: ipv6_list_of_tables
    run_list:
      - recipe[smoke::ipv6_tables]
    attributes:
